# Generated by Django 4.2.25 on 2025-10-24 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerequest',
            name='event_coordinator_faculty',
            field=models.ForeignKey(blank=True, help_text='Faculty member who is the event coordinator (can approve first)', limit_choices_to={'role': 'Faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
