# Generated by Django 4.2.25 on 2025-10-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerequest_event_coordinator_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerequest',
            name='period_faculty_mapping',
            field=models.JSONField(default=dict, blank=True),
        ),
    ]
